#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("UniBlu.Resource", IsApplication=true)]

namespace UniBlu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int numberOfShakes = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int screenShake = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0b0000
			public const int language_array = 2131427328;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int cardBackgroundColor = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int cardCornerRadius = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int cardElevation = 2130771970;
			
			// aapt resource value: 0x7f010003
			public const int cardMaxElevation = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int cardPreventCornerOverlap = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int cardUseCompatPadding = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int contentPadding = 2130771974;
			
			// aapt resource value: 0x7f01000a
			public const int contentPaddingBottom = 2130771978;
			
			// aapt resource value: 0x7f010007
			public const int contentPaddingLeft = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int contentPaddingRight = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int contentPaddingTop = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f080005
			public const int black = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int blueText = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int cardview_dark_background = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int cardview_light_background = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int cardview_shadow_end_color = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int cardview_shadow_start_color = 2131230723;
			
			// aapt resource value: 0x7f080008
			public const int grayRowColor = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int uniblue = 2131230727;
			
			// aapt resource value: 0x7f080004
			public const int white = 2131230724;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090000
			public const int cardview_compat_inset_shadow = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int cardview_default_elevation = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int cardview_default_radius = 2131296258;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Alpha = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int delta = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Heart = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int LabSchedule1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int leftArrow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int logo2 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int logo2Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int logoIcon = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int sigma = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int UniBlu = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0d0016
			public const int CISFragmentContainer = 2131558422;
			
			// aapt resource value: 0x7f0d0015
			public const int CISWebView = 2131558421;
			
			// aapt resource value: 0x7f0d0066
			public const int about = 2131558502;
			
			// aapt resource value: 0x7f0d005a
			public const int addCourseButton = 2131558490;
			
			// aapt resource value: 0x7f0d005b
			public const int addFilterButton = 2131558491;
			
			// aapt resource value: 0x7f0d004a
			public const int announcementButton = 2131558474;
			
			// aapt resource value: 0x7f0d000f
			public const int announcementCloseButton = 2131558415;
			
			// aapt resource value: 0x7f0d0014
			public const int announcementContentTextView = 2131558420;
			
			// aapt resource value: 0x7f0d0011
			public const int announcementDateTextView = 2131558417;
			
			// aapt resource value: 0x7f0d0041
			public const int announcementListView = 2131558465;
			
			// aapt resource value: 0x7f0d0012
			public const int announcementPostedByTextView = 2131558418;
			
			// aapt resource value: 0x7f0d0013
			public const int announcementPostedToTextView = 2131558419;
			
			// aapt resource value: 0x7f0d000b
			public const int announcementTitleTextView = 2131558411;
			
			// aapt resource value: 0x7f0d0000
			public const int card_view = 2131558400;
			
			// aapt resource value: 0x7f0d005f
			public const int clearCalendarButton = 2131558495;
			
			// aapt resource value: 0x7f0d0057
			public const int confirmPasswordEditText = 2131558487;
			
			// aapt resource value: 0x7f0d0056
			public const int confirmPasswordTextView = 2131558486;
			
			// aapt resource value: 0x7f0d000e
			public const int contentTextView = 2131558414;
			
			// aapt resource value: 0x7f0d0040
			public const int courseListView = 2131558464;
			
			// aapt resource value: 0x7f0d0049
			public const int coursePlannerButton = 2131558473;
			
			// aapt resource value: 0x7f0d0005
			public const int createFilterTitleTextView = 2131558405;
			
			// aapt resource value: 0x7f0d0006
			public const int dayOffButton = 2131558406;
			
			// aapt resource value: 0x7f0d0018
			public const int daysOfWeek = 2131558424;
			
			// aapt resource value: 0x7f0d0009
			public const int doneWithFilterButton = 2131558409;
			
			// aapt resource value: 0x7f0d0064
			public const int downloadData = 2131558500;
			
			// aapt resource value: 0x7f0d0010
			public const int fragmentContainer = 2131558416;
			
			// aapt resource value: 0x7f0d0008
			public const int freeLunchButton = 2131558408;
			
			// aapt resource value: 0x7f0d001d
			public const int friday = 2131558429;
			
			// aapt resource value: 0x7f0d003e
			public const int fridayRadioButton = 2131558462;
			
			// aapt resource value: 0x7f0d0039
			public const int goToCoursePlannerButton = 2131558457;
			
			// aapt resource value: 0x7f0d0007
			public const int hateEarlyMorningsButton = 2131558407;
			
			// aapt resource value: 0x7f0d0048
			public const int imageView1 = 2131558472;
			
			// aapt resource value: 0x7f0d0045
			public const int instructorBioListView = 2131558469;
			
			// aapt resource value: 0x7f0d004b
			public const int instructorBiosButton = 2131558475;
			
			// aapt resource value: 0x7f0d0003
			public const int jamesImageView = 2131558403;
			
			// aapt resource value: 0x7f0d0004
			public const int jamesTextView = 2131558404;
			
			// aapt resource value: 0x7f0d004c
			public const int labSchedulesButton = 2131558476;
			
			// aapt resource value: 0x7f0d0047
			public const int labSchedulesWebView = 2131558471;
			
			// aapt resource value: 0x7f0d0046
			public const int linearLayout1 = 2131558470;
			
			// aapt resource value: 0x7f0d0059
			public const int linearLayout2 = 2131558489;
			
			// aapt resource value: 0x7f0d005d
			public const int linearLayout3 = 2131558493;
			
			// aapt resource value: 0x7f0d0052
			public const int loginButton = 2131558482;
			
			// aapt resource value: 0x7f0d000a
			public const int mainScrollView = 2131558410;
			
			// aapt resource value: 0x7f0d0019
			public const int monday = 2131558425;
			
			// aapt resource value: 0x7f0d003a
			public const int mondayRadioButton = 2131558458;
			
			// aapt resource value: 0x7f0d0051
			public const int notRegistered = 2131558481;
			
			// aapt resource value: 0x7f0d003f
			public const int okButton = 2131558463;
			
			// aapt resource value: 0x7f0d0050
			public const int passwordEditText = 2131558480;
			
			// aapt resource value: 0x7f0d0055
			public const int passwordTextView = 2131558485;
			
			// aapt resource value: 0x7f0d000c
			public const int postedByTextView = 2131558412;
			
			// aapt resource value: 0x7f0d000d
			public const int postedToTextView = 2131558413;
			
			// aapt resource value: 0x7f0d0063
			public const int printScreen = 2131558499;
			
			// aapt resource value: 0x7f0d0044
			public const int professorBioTextView = 2131558468;
			
			// aapt resource value: 0x7f0d0042
			public const int professorImageView = 2131558466;
			
			// aapt resource value: 0x7f0d0043
			public const int professorNameTextView = 2131558467;
			
			// aapt resource value: 0x7f0d0058
			public const int registerButton = 2131558488;
			
			// aapt resource value: 0x7f0d005c
			public const int removeFromCalendarButton = 2131558492;
			
			// aapt resource value: 0x7f0d005e
			public const int saveCalendarButton = 2131558494;
			
			// aapt resource value: 0x7f0d0060
			public const int schedulesFragmentContainer = 2131558496;
			
			// aapt resource value: 0x7f0d0065
			public const int search = 2131558501;
			
			// aapt resource value: 0x7f0d0053
			public const int selectUserNameTextView = 2131558483;
			
			// aapt resource value: 0x7f0d0062
			public const int settings = 2131558498;
			
			// aapt resource value: 0x7f0d0001
			public const int soniaImageView = 2131558401;
			
			// aapt resource value: 0x7f0d0002
			public const int soniaTextView = 2131558402;
			
			// aapt resource value: 0x7f0d004d
			public const int studentSocietyButton = 2131558477;
			
			// aapt resource value: 0x7f0d0017
			public const int tableLayout1 = 2131558423;
			
			// aapt resource value: 0x7f0d0026
			public const int tableRow10 = 2131558438;
			
			// aapt resource value: 0x7f0d0027
			public const int tableRow11 = 2131558439;
			
			// aapt resource value: 0x7f0d0028
			public const int tableRow12 = 2131558440;
			
			// aapt resource value: 0x7f0d0029
			public const int tableRow13 = 2131558441;
			
			// aapt resource value: 0x7f0d002a
			public const int tableRow14 = 2131558442;
			
			// aapt resource value: 0x7f0d002b
			public const int tableRow15 = 2131558443;
			
			// aapt resource value: 0x7f0d002c
			public const int tableRow16 = 2131558444;
			
			// aapt resource value: 0x7f0d002d
			public const int tableRow17 = 2131558445;
			
			// aapt resource value: 0x7f0d002e
			public const int tableRow18 = 2131558446;
			
			// aapt resource value: 0x7f0d002f
			public const int tableRow19 = 2131558447;
			
			// aapt resource value: 0x7f0d001e
			public const int tableRow2 = 2131558430;
			
			// aapt resource value: 0x7f0d0030
			public const int tableRow20 = 2131558448;
			
			// aapt resource value: 0x7f0d0031
			public const int tableRow21 = 2131558449;
			
			// aapt resource value: 0x7f0d0032
			public const int tableRow22 = 2131558450;
			
			// aapt resource value: 0x7f0d0033
			public const int tableRow23 = 2131558451;
			
			// aapt resource value: 0x7f0d0034
			public const int tableRow24 = 2131558452;
			
			// aapt resource value: 0x7f0d0035
			public const int tableRow25 = 2131558453;
			
			// aapt resource value: 0x7f0d0036
			public const int tableRow26 = 2131558454;
			
			// aapt resource value: 0x7f0d0037
			public const int tableRow27 = 2131558455;
			
			// aapt resource value: 0x7f0d0038
			public const int tableRow28 = 2131558456;
			
			// aapt resource value: 0x7f0d001f
			public const int tableRow3 = 2131558431;
			
			// aapt resource value: 0x7f0d0020
			public const int tableRow4 = 2131558432;
			
			// aapt resource value: 0x7f0d0021
			public const int tableRow5 = 2131558433;
			
			// aapt resource value: 0x7f0d0022
			public const int tableRow6 = 2131558434;
			
			// aapt resource value: 0x7f0d0023
			public const int tableRow7 = 2131558435;
			
			// aapt resource value: 0x7f0d0024
			public const int tableRow8 = 2131558436;
			
			// aapt resource value: 0x7f0d0025
			public const int tableRow9 = 2131558437;
			
			// aapt resource value: 0x7f0d004e
			public const int textView1 = 2131558478;
			
			// aapt resource value: 0x7f0d001c
			public const int thursday = 2131558428;
			
			// aapt resource value: 0x7f0d003d
			public const int thursdayRadioButton = 2131558461;
			
			// aapt resource value: 0x7f0d0061
			public const int toolbar = 2131558497;
			
			// aapt resource value: 0x7f0d001a
			public const int tuesday = 2131558426;
			
			// aapt resource value: 0x7f0d003b
			public const int tuesdayRadioButton = 2131558459;
			
			// aapt resource value: 0x7f0d0054
			public const int userNameEditText = 2131558484;
			
			// aapt resource value: 0x7f0d004f
			public const int usernameEditText = 2131558479;
			
			// aapt resource value: 0x7f0d001b
			public const int wednesday = 2131558427;
			
			// aapt resource value: 0x7f0d003c
			public const int wednesdayRadioButton = 2131558460;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int aboutLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int addFilterLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int AnnouncementDetailView = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int AnnouncementMenuView = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int AnnouncementRowView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int CISFragment = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int CISLayout = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int CoreCourseFragment = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int CourseMenuView = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int CourseRowView = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int CourseScheduleLayout = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int DayOffLayout = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ElectivesFragment = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int GNEDFragment = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int InstructorAnnouncementFragment = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int InstructorBioDetailView = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int InstructorBioListView = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int InstructorBiosView = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int LabSchedulesFragment = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int LandingPageView = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Main = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ProgramAnnouncementFragment = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int ProgramCoursesFragment = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int registrationLayout = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int SchedulePlannerLayout = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int SchedulesView = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int StudentSocietyAnnouncementFragment = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int toolbar = 2130903067;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0c0000
			public const int hateEarlyMorningsPopupMenu = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int SettingsMenu = 2131492865;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int pomp_loop = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0a001a
			public const int aboutJames = 2131361818;
			
			// aapt resource value: 0x7f0a001b
			public const int aboutRyan = 2131361819;
			
			// aapt resource value: 0x7f0a0019
			public const int aboutSonia = 2131361817;
			
			// aapt resource value: 0x7f0a001c
			public const int aboutUs = 2131361820;
			
			// aapt resource value: 0x7f0a0018
			public const int about_label = 2131361816;
			
			// aapt resource value: 0x7f0a002b
			public const int addAFilter = 2131361835;
			
			// aapt resource value: 0x7f0a003d
			public const int addCourseButton = 2131361853;
			
			// aapt resource value: 0x7f0a0045
			public const int addCourseTitle = 2131361861;
			
			// aapt resource value: 0x7f0a003e
			public const int addFilterButton = 2131361854;
			
			// aapt resource value: 0x7f0a0008
			public const int announcementsButton = 2131361800;
			
			// aapt resource value: 0x7f0a0039
			public const int announcementsTitle = 2131361849;
			
			// aapt resource value: 0x7f0a0001
			public const int appName = 2131361793;
			
			// aapt resource value: 0x7f0a0036
			public const int cisFaceBook = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int cisTitle = 2131361847;
			
			// aapt resource value: 0x7f0a003f
			public const int clearCalendarButton = 2131361855;
			
			// aapt resource value: 0x7f0a0021
			public const int confirmPassword = 2131361825;
			
			// aapt resource value: 0x7f0a0007
			public const int coursePlannerButton = 2131361799;
			
			// aapt resource value: 0x7f0a003c
			public const int courseScheduleTitle = 2131361852;
			
			// aapt resource value: 0x7f0a0026
			public const int createFilterTitle = 2131361830;
			
			// aapt resource value: 0x7f0a003b
			public const int currentSchedule = 2131361851;
			
			// aapt resource value: 0x7f0a0027
			public const int dayOffFilter = 2131361831;
			
			// aapt resource value: 0x7f0a002a
			public const int doneWithFilter = 2131361834;
			
			// aapt resource value: 0x7f0a0016
			public const int downloadData_label = 2131361814;
			
			// aapt resource value: 0x7f0a0029
			public const int freeLunchFilter = 2131361833;
			
			// aapt resource value: 0x7f0a0030
			public const int friday = 2131361840;
			
			// aapt resource value: 0x7f0a0043
			public const int goToCoursePlannerButton = 2131361859;
			
			// aapt resource value: 0x7f0a0028
			public const int hateEarlyMorningsFilter = 2131361832;
			
			// aapt resource value: 0x7f0a0044
			public const int hours = 2131361860;
			
			// aapt resource value: 0x7f0a0038
			public const int instructor = 2131361848;
			
			// aapt resource value: 0x7f0a0009
			public const int instructorBiosButton = 2131361801;
			
			// aapt resource value: 0x7f0a0025
			public const int instructors = 2131361829;
			
			// aapt resource value: 0x7f0a000a
			public const int labSchedulesButton = 2131361802;
			
			// aapt resource value: 0x7f0a0014
			public const int language_prompt = 2131361812;
			
			// aapt resource value: 0x7f0a0006
			public const int loginButton = 2131361798;
			
			// aapt resource value: 0x7f0a002c
			public const int monday = 2131361836;
			
			// aapt resource value: 0x7f0a000f
			public const int music_summary = 2131361807;
			
			// aapt resource value: 0x7f0a000e
			public const int music_title = 2131361806;
			
			// aapt resource value: 0x7f0a0033
			public const int notBefore10_label = 2131361843;
			
			// aapt resource value: 0x7f0a0034
			public const int notBefore11_label = 2131361844;
			
			// aapt resource value: 0x7f0a0032
			public const int notBefore9_label = 2131361842;
			
			// aapt resource value: 0x7f0a001e
			public const int notRegistered = 2131361822;
			
			// aapt resource value: 0x7f0a0031
			public const int ok = 2131361841;
			
			// aapt resource value: 0x7f0a0003
			public const int password = 2131361795;
			
			// aapt resource value: 0x7f0a0005
			public const int passwordHint = 2131361797;
			
			// aapt resource value: 0x7f0a0015
			public const int printScreen_label = 2131361813;
			
			// aapt resource value: 0x7f0a0023
			public const int registerButton = 2131361827;
			
			// aapt resource value: 0x7f0a0022
			public const int registration = 2131361826;
			
			// aapt resource value: 0x7f0a0041
			public const int removeFromCalendarButton = 2131361857;
			
			// aapt resource value: 0x7f0a0040
			public const int saveCalendarButton = 2131361856;
			
			// aapt resource value: 0x7f0a0013
			public const int saveReadAnnouncements_summary = 2131361811;
			
			// aapt resource value: 0x7f0a0012
			public const int saveReadAnnouncements_title = 2131361810;
			
			// aapt resource value: 0x7f0a0042
			public const int schedulePlannerTitle = 2131361858;
			
			// aapt resource value: 0x7f0a003a
			public const int schedulesTitle = 2131361850;
			
			// aapt resource value: 0x7f0a0011
			public const int scrollingScreen_summary = 2131361809;
			
			// aapt resource value: 0x7f0a0010
			public const int scrollingScreen_title = 2131361808;
			
			// aapt resource value: 0x7f0a0017
			public const int search_label = 2131361815;
			
			// aapt resource value: 0x7f0a0035
			public const int selectDayOff = 2131361845;
			
			// aapt resource value: 0x7f0a0020
			public const int selectPassword = 2131361824;
			
			// aapt resource value: 0x7f0a001f
			public const int selectUserName = 2131361823;
			
			// aapt resource value: 0x7f0a000c
			public const int settings_label = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int settings_title = 2131361805;
			
			// aapt resource value: 0x7f0a001d
			public const int sorryNotDone = 2131361821;
			
			// aapt resource value: 0x7f0a000b
			public const int studentSocietyButton = 2131361803;
			
			// aapt resource value: 0x7f0a0024
			public const int thankYouForRegistering = 2131361828;
			
			// aapt resource value: 0x7f0a002f
			public const int thursday = 2131361839;
			
			// aapt resource value: 0x7f0a002d
			public const int tuesday = 2131361837;
			
			// aapt resource value: 0x7f0a0002
			public const int username = 2131361794;
			
			// aapt resource value: 0x7f0a0004
			public const int usernameHint = 2131361796;
			
			// aapt resource value: 0x7f0a002e
			public const int wednesday = 2131361838;
			
			// aapt resource value: 0x7f0a0000
			public const int welcome = 2131361792;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070001
			public const int Base_CardView = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int CardView = 2131165184;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int CardView_Light = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int MyTheme = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int TabTheme = 2131165189;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int Settings = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[]
			{
					16843071,
					16843072,
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
