#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UniBlu.Resource", IsApplication=true)]

namespace UniBlu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080000
			public const int language_array = 2131230720;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int black = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int blueText = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int white = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Alpha = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int delta = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Heart = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logoIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sigma = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int UniBlu = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0b0013
			public const int about = 2131427347;
			
			// aapt resource value: 0x7f0b0006
			public const int announcementButton = 2131427334;
			
			// aapt resource value: 0x7f0b0005
			public const int coursePlannerButton = 2131427333;
			
			// aapt resource value: 0x7f0b0011
			public const int downloadData = 2131427345;
			
			// aapt resource value: 0x7f0b0004
			public const int imageView1 = 2131427332;
			
			// aapt resource value: 0x7f0b0007
			public const int instructorBiosButton = 2131427335;
			
			// aapt resource value: 0x7f0b0002
			public const int jamesImageView = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int jamesTextView = 2131427331;
			
			// aapt resource value: 0x7f0b0008
			public const int labSchedulesButton = 2131427336;
			
			// aapt resource value: 0x7f0b000e
			public const int loginButton = 2131427342;
			
			// aapt resource value: 0x7f0b000d
			public const int passwordEditText = 2131427341;
			
			// aapt resource value: 0x7f0b0010
			public const int printScreen = 2131427344;
			
			// aapt resource value: 0x7f0b0012
			public const int search = 2131427346;
			
			// aapt resource value: 0x7f0b000f
			public const int settings = 2131427343;
			
			// aapt resource value: 0x7f0b0000
			public const int soniaImageView = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int soniaTextView = 2131427329;
			
			// aapt resource value: 0x7f0b0009
			public const int studentSocietyButton = 2131427337;
			
			// aapt resource value: 0x7f0b000b
			public const int textView1 = 2131427339;
			
			// aapt resource value: 0x7f0b000a
			public const int toolbar = 2131427338;
			
			// aapt resource value: 0x7f0b000c
			public const int usernameEditText = 2131427340;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int aboutLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LandingPageView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int toolbar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0a0000
			public const int SettingsMenu = 2131361792;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int pomp_loop = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070018
			public const int aboutJames = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int aboutRyan = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int aboutSonia = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int aboutUs = 2131165210;
			
			// aapt resource value: 0x7f070016
			public const int about_label = 2131165206;
			
			// aapt resource value: 0x7f070008
			public const int announcementsButton = 2131165192;
			
			// aapt resource value: 0x7f070001
			public const int appName = 2131165185;
			
			// aapt resource value: 0x7f070007
			public const int coursePlannerButton = 2131165191;
			
			// aapt resource value: 0x7f070014
			public const int downloadData_label = 2131165204;
			
			// aapt resource value: 0x7f070009
			public const int instructorBiosButton = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int labSchedulesButton = 2131165194;
			
			// aapt resource value: 0x7f070012
			public const int language_prompt = 2131165202;
			
			// aapt resource value: 0x7f070006
			public const int loginButton = 2131165190;
			
			// aapt resource value: 0x7f07000f
			public const int music_summary = 2131165199;
			
			// aapt resource value: 0x7f07000e
			public const int music_title = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int password = 2131165187;
			
			// aapt resource value: 0x7f070005
			public const int passwordHint = 2131165189;
			
			// aapt resource value: 0x7f070013
			public const int printScreen_label = 2131165203;
			
			// aapt resource value: 0x7f070011
			public const int scrollingScreen_summary = 2131165201;
			
			// aapt resource value: 0x7f070010
			public const int scrollingScreen_title = 2131165200;
			
			// aapt resource value: 0x7f070015
			public const int search_label = 2131165205;
			
			// aapt resource value: 0x7f07000c
			public const int settings_label = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int settings_title = 2131165197;
			
			// aapt resource value: 0x7f07000b
			public const int studentSocietyButton = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int username = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int usernameHint = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int welcome = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f090000
			public const int MyTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Settings = 2130968576;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
