#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("UniBlu.Resource", IsApplication=true)]

namespace UniBlu
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int numberOfShakes = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int screenShake = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090000
			public const int language_array = 2131296256;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f070001
			public const int black = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int blueText = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int white = 2131165184;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Alpha = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int delta = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Heart = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int logo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int logo2 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int logoIcon = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int sigma = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int UniBlu = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0013
			public const int about = 2131492883;
			
			// aapt resource value: 0x7f0c0006
			public const int announcementButton = 2131492870;
			
			// aapt resource value: 0x7f0c0005
			public const int coursePlannerButton = 2131492869;
			
			// aapt resource value: 0x7f0c0011
			public const int downloadData = 2131492881;
			
			// aapt resource value: 0x7f0c0004
			public const int imageView1 = 2131492868;
			
			// aapt resource value: 0x7f0c0007
			public const int instructorBiosButton = 2131492871;
			
			// aapt resource value: 0x7f0c0002
			public const int jamesImageView = 2131492866;
			
			// aapt resource value: 0x7f0c0003
			public const int jamesTextView = 2131492867;
			
			// aapt resource value: 0x7f0c0008
			public const int labSchedulesButton = 2131492872;
			
			// aapt resource value: 0x7f0c000d
			public const int loginButton = 2131492877;
			
			// aapt resource value: 0x7f0c000c
			public const int passwordEditText = 2131492876;
			
			// aapt resource value: 0x7f0c0010
			public const int printScreen = 2131492880;
			
			// aapt resource value: 0x7f0c0012
			public const int search = 2131492882;
			
			// aapt resource value: 0x7f0c000f
			public const int settings = 2131492879;
			
			// aapt resource value: 0x7f0c0000
			public const int soniaImageView = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int soniaTextView = 2131492865;
			
			// aapt resource value: 0x7f0c0009
			public const int studentSocietyButton = 2131492873;
			
			// aapt resource value: 0x7f0c000a
			public const int textView1 = 2131492874;
			
			// aapt resource value: 0x7f0c000e
			public const int toolbar = 2131492878;
			
			// aapt resource value: 0x7f0c000b
			public const int usernameEditText = 2131492875;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int aboutLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LandingPageView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int toolbar = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int SettingsMenu = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int pomp_loop = 2131099648;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080018
			public const int aboutJames = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int aboutRyan = 2131230745;
			
			// aapt resource value: 0x7f080017
			public const int aboutSonia = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int aboutUs = 2131230746;
			
			// aapt resource value: 0x7f080016
			public const int about_label = 2131230742;
			
			// aapt resource value: 0x7f080008
			public const int announcementsButton = 2131230728;
			
			// aapt resource value: 0x7f080001
			public const int appName = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int coursePlannerButton = 2131230727;
			
			// aapt resource value: 0x7f080014
			public const int downloadData_label = 2131230740;
			
			// aapt resource value: 0x7f080009
			public const int instructorBiosButton = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int labSchedulesButton = 2131230730;
			
			// aapt resource value: 0x7f080012
			public const int language_prompt = 2131230738;
			
			// aapt resource value: 0x7f080006
			public const int loginButton = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int music_summary = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int music_title = 2131230734;
			
			// aapt resource value: 0x7f080003
			public const int password = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int passwordHint = 2131230725;
			
			// aapt resource value: 0x7f080013
			public const int printScreen_label = 2131230739;
			
			// aapt resource value: 0x7f080011
			public const int scrollingScreen_summary = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int scrollingScreen_title = 2131230736;
			
			// aapt resource value: 0x7f080015
			public const int search_label = 2131230741;
			
			// aapt resource value: 0x7f08000c
			public const int settings_label = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int settings_title = 2131230733;
			
			// aapt resource value: 0x7f08001b
			public const int sorryNotDone = 2131230747;
			
			// aapt resource value: 0x7f08000b
			public const int studentSocietyButton = 2131230731;
			
			// aapt resource value: 0x7f080002
			public const int username = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int usernameHint = 2131230724;
			
			// aapt resource value: 0x7f080000
			public const int welcome = 2131230720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int MyTheme = 2131361792;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f050000
			public const int Settings = 2131034112;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
